version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu


#hooks:
#  AfterInstall:
#    - location: ./start.sh
#      timeout: 60
#      runas: ubuntu

hooks:
  AfterInstall:
    - location: ./stop.sh
      timeout: 1000
      runas: ubuntu
  ApplicationStart:
    - location: ./start.sh
      timeout: 1000
      runas: ubuntu